export const ScreenId = Object.freeze({
  WELCOME_ROLE_SELECT: 'WELCOME_ROLE_SELECT',

  LANDLORD_REG_NAME: 'LANDLORD_REG_NAME',
  LANDLORD_REG_PHONE: 'LANDLORD_REG_PHONE',
  LANDLORD_REG_OTP: 'LANDLORD_REG_OTP',
  LANDLORD_AUTHENTICATED: 'LANDLORD_AUTHENTICATED',

  TENANT_REG_NAME: 'TENANT_REG_NAME',
  TENANT_REG_PHONE: 'TENANT_REG_PHONE',
  TENANT_REG_OTP: 'TENANT_REG_OTP',
  TENANT_REG_PROP_CODE: 'TENANT_REG_PROP_CODE',
  TENANT_AUTHENTICATED: 'TENANT_AUTHENTICATED',

  HELP_LANDLORD: 'HELP_LANDLORD',
  HELP_TENANT: 'HELP_TENANT',

  ERROR_GENERIC: 'ERROR_GENERIC',
  ERROR_INVALID_OTP: 'ERROR_INVALID_OTP',
  ERROR_OTP_EXPIRED: 'ERROR_OTP_EXPIRED',
  ERROR_RESEND_OTP: 'ERROR_RESEND_OTP',
  ERROR_ALREADY_REGISTERED: 'ERROR_ALREADY_REGISTERED',
  ERROR_INVALID_PROP_CODE: 'ERROR_INVALID_PROP_CODE',
  SESSION_EXPIRED: 'SESSION_EXPIRED',

  BUY_AMOUNT: 'BUY_AMOUNT',
  BUY_PROP_CODE: 'BUY_PROP_CODE',
  BUY_CONFIRM: 'BUY_CONFIRM',
  PAYMENT_INSTRUCTIONS_BANK: 'PAYMENT_INSTRUCTIONS_BANK',
  PAYMENT_INSTRUCTIONS_MOBILE_MONEY: 'PAYMENT_INSTRUCTIONS_MOBILE_MONEY',
  PAYMENT_INSTRUCTIONS_CRYPTO: 'PAYMENT_INSTRUCTIONS_CRYPTO',
  AWAITING_PAYMENT: 'AWAITING_PAYMENT',
  PAYMENT_CONFIRMED: 'PAYMENT_CONFIRMED',
  PAYMENT_EXPIRED: 'PAYMENT_EXPIRED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',

  BALANCE_VIEW: 'BALANCE_VIEW',
  HISTORY_VIEW: 'HISTORY_VIEW',
  MY_PROPERTY_VIEW: 'MY_PROPERTY_VIEW',

  MY_PROPERTIES_LIST: 'MY_PROPERTIES_LIST',
  ADD_PROPERTY_ADDRESS: 'ADD_PROPERTY_ADDRESS',
  ADD_PROPERTY_FLAT_COUNT: 'ADD_PROPERTY_FLAT_COUNT',
  ADD_PROPERTY_LABEL: 'ADD_PROPERTY_LABEL',
  PROPERTY_REGISTERED: 'PROPERTY_REGISTERED',
  PROPERTY_DETAIL: 'PROPERTY_DETAIL',
  TENANTS_LIST: 'TENANTS_LIST',

  EARNINGS_OVERVIEW: 'EARNINGS_OVERVIEW',
  EARNINGS_PROPERTY: 'EARNINGS_PROPERTY',
  WITHDRAW_BANK_INPUT: 'WITHDRAW_BANK_INPUT',
  WITHDRAW_BANK_NAME: 'WITHDRAW_BANK_NAME',
  WITHDRAW_ACCOUNT_INPUT: 'WITHDRAW_ACCOUNT_INPUT',
  WITHDRAW_CONFIRM: 'WITHDRAW_CONFIRM',
  WITHDRAWAL_INITIATED: 'WITHDRAWAL_INITIATED',

  REMOVE_TENANT_PROPERTY: 'REMOVE_TENANT_PROPERTY',
  REMOVE_TENANT_PHONE: 'REMOVE_TENANT_PHONE',
  REMOVE_TENANT_CONFIRM: 'REMOVE_TENANT_CONFIRM',
  TENANT_REMOVED_LANDLORD: 'TENANT_REMOVED_LANDLORD',

  ALERT_LOW_BALANCE: 'ALERT_LOW_BALANCE',
  ALERT_CUTOFF: 'ALERT_CUTOFF',
  ALERT_RESTORED: 'ALERT_RESTORED',
  NOTIFY_NEW_TENANT: 'NOTIFY_NEW_TENANT',
  NOTIFY_PURCHASE_CONFIRMED: 'NOTIFY_PURCHASE_CONFIRMED',
  NOTIFY_WITHDRAWAL_CONFIRMED: 'NOTIFY_WITHDRAWAL_CONFIRMED',
  NOTIFY_TENANT_REMOVED: 'NOTIFY_TENANT_REMOVED',

  OTP_SENT: 'OTP_SENT',
  OTP_INVALID: 'OTP_INVALID',
  OTP_RESENT: 'OTP_RESENT',

  ROLE_PROMPT: 'ROLE_PROMPT',
  REGISTRATION_SUCCESS: 'REGISTRATION_SUCCESS',
  ALREADY_REGISTERED: 'ALREADY_REGISTERED',
});

export const INTERNAL_SCREEN_IDS = new Set([
  ScreenId.LANDLORD_AUTHENTICATED,
  ScreenId.TENANT_AUTHENTICATED,
  ScreenId.AWAITING_PAYMENT,
]);

export const ALL_SCREEN_IDS = Object.freeze(Object.values(ScreenId));

export function isScreenId(value) {
  return ALL_SCREEN_IDS.includes(value);
}
